### ISSUE TITLE
ENOENT: no such file or directory, stat '/Users/USER/pinokio/api/deus.git/{{input.event[1]}}'

### ISSUE THREAD

**Issue by aqgasa** [cocktailpeanut/deus#1]
I used Pinokio (Version 0.2.5) to install deus on a Mac mini M2 Pro.

When trying to lauch deus, it opens a blank white window with the following text:
ENOENT: no such file or directory, stat '/Users/USER/pinokio/api/deus.git/{{input.event[1]}}'

---- This is the output in Pinokio:

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ source /Users/USER/pinokio/api/deus.git/server/env/bin/activate /Users/USER/pinokio/api/deus.git/server/env && uvicorn app:app
/Users/USER/pinokio/api/deus.git/server/env/lib/python3.10/site-packages/huggingface_hub/file_download.py:672: FutureWarning: 'cached_download' is the legacy way to download files from the HF hub, please consider upgrading to 'hf_hub_download'
  warnings.warn(
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 20.32it/s]
/Users/USER/pinokio/api/deus.git/server/env/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py:749: FutureWarning: `torch_dtype` is deprecated and will be removed in version 0.25.0. 
  deprecate("torch_dtype", "0.25.0", "")
/Users/USER/pinokio/api/deus.git/server/env/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py:752: FutureWarning: `torch_device` is deprecated and will be removed in version 0.25.0. 
  deprecate("torch_device", "0.25.0", "")
INFO:     Started server process [97460]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ npm run dev

> client@0.1.0 dev
> next dev

undefined:66
var Pe = /[$_\p{ID_Start}]/u;
         ^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid regular expression: /[$_\p{ID_Start}]/: Invalid property name in character class
    at requireWithFakeGlobalScope (/Users/USER/pinokio/api/deus.git/client/node_modules/next/dist/compiled/@edge-runtime/primitives/load.js:65:8)
    at load (/Users/USER/pinokio/api/deus.git/client/node_modules/next/dist/compiled/@edge-runtime/primitives/load.js:141:19)
    at Object.<anonymous> (/Users/USER/pinokio/api/deus.git/client/node_modules/next/dist/compiled/@edge-runtime/primitives/index.js:5:39)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at mod.require (/Users/USER/pinokio/api/deus.git/client/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:110:18)

Node.js v18.16.0
bash-3.2$

**Comment by jrikkerink** [comment]
Have the same problem here on Windows 10..

**Comment by Akulla3D** [comment]
Has this been fixed or is there a work around.  Having same issue with windows.
